// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// //import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCj72Fd7FFKAvAY4P6hxj185s6i21wlEQ4',
//     appId: '1:725973648205:android:7b94c6191e8f72d58d2d04',
//     messagingSenderId: '725973648205',
//     projectId: 'spa-app-6ff6c',
//     storageBucket: 'spa-app-6ff6c.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCGbW_cQBKJKul9sH1ZfsCa-5zpMYUtAtg',
//     appId: '1:725973648205:ios:47acdb259c0013898d2d04',
//     messagingSenderId: '725973648205',
//     projectId: 'spa-app-6ff6c',
//     storageBucket: 'spa-app-6ff6c.appspot.com',
//     iosClientId: '725973648205-e6bpt6dm7fujvqidcdjg6hbo4vb5phl5.apps.googleusercontent.com',
//     iosBundleId: 'com.example.testApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCGbW_cQBKJKul9sH1ZfsCa-5zpMYUtAtg',
//     appId: '1:725973648205:ios:b51a908a0c1607488d2d04',
//     messagingSenderId: '725973648205',
//     projectId: 'spa-app-6ff6c',
//     storageBucket: 'spa-app-6ff6c.appspot.com',
//     iosClientId: '725973648205-5f0dg1cdjoktc8840s0e509rjfqr2tdq.apps.googleusercontent.com',
//     iosBundleId: 'com.example.testApp.RunnerTests',
//   );
// }
